name: Auto-Publish
on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  main:
    name: Compile and deploy
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install bikeshed
            
          cd conformance
          poetry install

      - name: Generate conformance report
        run: |
          poetry run generate-report

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Build conformance page
        run: |
          cd conformance_page
          npm ci
          npm run build

      - name: Run bikeshed
        run: |
          bikeshed spec
          mkdir dist
          cp *.html dist
          cp -r images dist
          # mkdir dist/conformance
          # cp -r conformance/conformance_page/dist/* dist/conformance

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
